### ISSUE TITLE
Information about the deprecation of the paper-toolbar.

### ISSUE THREAD

**Issue by rene-lindner-isw** [PolymerElements/paper-toolbar#107]
### Description
Sorry for opening an issue for this, but i haven't received any feedback in the google group for the last two weeks, and i would really need some infos on this.
https://groups.google.com/forum/#!topic/polymer-dev/_4BYY_MzHQc

As far as i understood the app-layout elements they were introduced as non-material-design alternatives for the paper-elements, so they are no MD elements.

* Will e.g. the app-toolbar ever implement the MD specs?
* Will there be an MD replacement for e.g. the paper-toolbar?
* For how long will the paper-toolbar be supported, will there be a stable 2.0 version?
* What is the intended way for an MD toolbar? Customize the app-toolbar?

Some information on that topic would be highly appreciated.

**Comment by frankiefu** [comment]
@rene-lindner-isw We tried to avoid using media queries inside layout elements because they can be used in many places and for different purposes. I'd recommend using media queries from outside the element. For example,
```
@media (max-width: 600px) {
  app-toolbar {
    height: 56px;
    padding: 0 8px;
  }
}
```
This should be all you need to get `app-toolbar` responsive follows MD spec.  We are also working on adding [MD Responsive Toolbar pattern](https://github.com/PolymerElements/app-layout/tree/md-toolbar-pattern#patterns) and the [source](https://github.com/PolymerElements/app-layout/blob/md-toolbar-pattern/patterns/md-responsive-toolbar/index.html).

As with paper-toolbar, there is going to be paper-toolbar 2.0 release but I'd suggest to just start using app-layout since paper-toolbar is going to be deprecated.  And if you have any issues using app layout elements please file them in [github](https://github.com/PolymerElements/app-layout) and we will try to address them.

HTH.

**Comment by rene-lindner-isw** [comment]
That makes sense, thanks for your feedback!

**Comment by rene-lindner-isw** [comment]
Just tried to build something like this
https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3NERlZTZ0MFRJekE/layout_structure_sidenav_structure4.png
for our app, but it takes quite some styling, since multiple rows are not supported by the app-toolbar.

Ended up styling an own MD toolbar.
https://www.webcomponents.org/element/IswPolymerElements/isw-toolbar
Followed your advice that no media queries should be used inside an element, added a metrics property that can be "mobile" or "tablet" and can be controlled by the app.
