### ISSUE TITLE
Non-tall paper-toolbar + paper-icon-button doesn't work in IE10

### ISSUE THREAD

**Issue by rfc2822** [PolymerElements/paper-toolbar#30]
I have found this issue in my own Polymer-based web app, but it also happens in the demo. Steps to reproduce:
1. Open https://elements.polymer-project.org/bower_components/paper-toolbar/demo/index.html in IE10
2. In the first toolbar (the one without `class=tall`), the buttons are only clickable on a few pixels, and when you click them, nothing happens.
3. All other toolbars work fine.

paper-toolbar v1.0.2, paper-icon-button v1.0.2

**Comment by blasten** [comment]
This is confirmed.

**Comment by rbellens** [comment]
I had the same issue. The reason seems to be the top, bottom and middle div's that are placed over each other on non tall toolbars. MouseEvents are only handled by the bottom div. Adding class="bottom" to the content of the toolbar fixes this (content is added to the bottom div in stead of the default top div).

**Comment by kungufli** [comment]
This also breaks `paper-button`.

**Comment by rfc2822** [comment]
@rbellens Thanks for the workaround, using `class=bottom` for all child elements works here.

**Comment by kungufli** [comment]
@rbellens thanks for the workaround, works well for non-tall toolbar. But in my project I also have a tall toolbar where I need to place `paper-button` and `paper-icon-button` in the top section and this bug is still there, @blasten any news about that?
